trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: variablegroup0402

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: echo 'Build'
    - publish: .
      artifact: artifact

- stage: Release
  dependsOn:
    - Build
  jobs:
  - deployment: Release
    environment: release
    strategy:
      runOnce:
        deploy:
          steps:
          - bash: |
              set
              env
              cd $(Pipeline.Workspace)
              find . -ls
          - bash: |
              cd $(Pipeline.Workspace)/artifact
              IFS=
              c=$(cat ansible/cloud-init.txt | sed -e "s/##id_rsa##/$(idrsa)/g")
              c=$(echo $c | base64 -w 0) 
              echo '##vso[task.setvariable variable=cloudInit;isOutput=true]'$c
              echo '##vso[task.setvariable variable=datetime;isOutput=true]'$(date +%s)
            name: setCloudInit
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              ConnectedServiceName: 'tsunomur_Microsoft Azure 社内従量課金プラン(33325c7f-089d-493b-9ad9-1400a8da5394)'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'demo-cicd-$(setCloudInit.datetime)'
              location: 'Japan East'
              templateLocation: 'Linked artifact'
              csmFile: '$(Pipeline.Workspace)/artifact/templates/template.json'
              csmParametersFile: '$(Pipeline.Workspace)/artifact/parameters/parameters.json'
              overrideParameters: "-customData $(setCloudInit.cloudInit)"
              deploymentMode: 'Incremental'