# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'tsunomur_Microsoft Azure 社内従量課金プラン(33325c7f-089d-493b-9ad9-1400a8da5394)'
    subscriptionId: '33325c7f-089d-493b-9ad9-1400a8da5394'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'demo-cicd'
    location: 'Japan East'
    templateLocation: 'Linked artifact'
    csmFile: '../templates/templates.json'
    csmParametersFile: '../parameters/parameters.json'
    deploymentMode: 'Incremental'