trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: echo 'Build'
    - publish: .
      artifact: templates

- stage: Release
  dependsOn:
  - Build
  jobs:
  - job: Release
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        ConnectedServiceName: 'tsunomur_Microsoft Azure 社内従量課金プラン(33325c7f-089d-493b-9ad9-1400a8da5394)'
        #subscriptionName: 'tsunomur_Microsoft Azure 社内従量課金プラン(33325c7f-089d-493b-9ad9-1400a8da5394)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'demo-cicd'
        location: 'Japan East'
        templateLocation: 'Linked artifact'
        csmFile: 'templates/template.json'
        csmParametersFile: 'parameters/parameters.json'
        deploymentMode: 'Incremental'
    #- task: AzureResourceGroupDeployment@2
      #displayName: 'Azure Deployment:Create Or Update Resource Group action on demo-cicd2'
      #inputs:
        #azureSubscription: 'tsunomur_Microsoft Azure 社内従量課金プラン(33325c7f-089d-493b-9ad9-1400a8da5394)'
        #resourceGroupName: 'demo-cicd2'
        #location: 'Japan East'
        #csmFile: templates/template.json
        #csmParametersFile: parameters/parameters.json
    - task: Bash@3
      inputs:
          targetType: inline
          script: |
            set
            env
            find . -ls